spring:
  application:
    name: Nexiles OPC UA Client Example

logging:
  level:
    com.nexiles: DEBUG
    org.eclipse.milo: INFO
    org.apache.camel: DEBUG

nexiles:
  # endpoint: milo-client:tcp://opc-ua-demo-service.milo.svc.cluster.local:4840?allowedSecurityPolicies=None&node=RAW(ns=3;s="103_Servo_G"."M150_Data"."POS_ACT")
  # endpoint: milo-client:tcp://127.0.0.1:12686/example?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;s=HelloWorld/ScalarTypes/Double)
  endpoint: milo-client:tcp://opcua-build-env.milo.svc.cluster.local:12686/milo?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;s=HelloWorld/Dynamic/Double)

camel:
  component:
    milo-client:
      default-configuration:
        allowed-security-policies: None
        override-host: true
